sudo: required
services:
  - docker

before_install:
  -docker build -t justinforever/docker-react-learning -f Dockerfile.dev .

script:
  - docker run justinforever/docker-react-learning npm run test -- --coverage
