sudo: required
services:
  - docker

before_install:
  - docker build -t justinforever/docker-react-learning -f Dockerfile.dev .

script:
  - docker run -e CI=true justinforever/docker-react-learning npm run test -- --coverage
